export const GET_MOVIES = 'favorites/GET_MOVIES'
export const REMOVE_MOVIE = 'favorites/REMOVE_MOVIE'
export const REQUEST_MOVIES_START = 'favorites/REQUEST_MOVIES_START'
export const REQUEST_MOVIES_SUCCESS = 'favorites/REQUEST_MOVIES_SUCCESS'
export const REQUEST_MOVIES_ERROR = 'favorites/REQUEST_MOVIES_ERROR'
