export const GET_MOVIES = 'watchlist/GET_MOVIES'
export const REMOVE_MOVIE = 'watchlist/REMOVE_MOVIE'
export const REQUEST_MOVIES_START = 'watchlist/REQUEST_MOVIES_START'
export const REQUEST_MOVIES_SUCCESS = 'watchlist/REQUEST_MOVIES_SUCCESS'
export const REQUEST_MOVIES_ERROR = 'watchlist/REQUEST_MOVIES_ERROR'
