export const LOGIN_SUBMIT = 'auth/LOGIN_SUBMIT'
export const LOGIN_REQUEST = 'auth/LOGIN_REQUEST'
export const LOGIN_FAILS = 'auth/LOGIN_FAILS'
export const LOGIN_SUCCESS = 'auth/LOGIN_SUCCESS'
export const LOGIN_LOGOUT = 'auth/LOGIN_LOGOUT'
export const STORE_USER = 'auth/STORE_USER'
export const GET_USER = 'auth/GET_USER'
