export const LOGIN_SUBMIT = 'auth/LOGIN_SUBMIT'
export const LOGIN_REQUEST = 'auth/LOGIN_REQUEST'
export const LOGIN_SUBMIT_CANCEL = 'auth/LOGIN_SUBMIT_CANCEL'
export const LOGIN_FAILS = 'auth/LOGIN_FAILS'
export const LOGIN_SUCCESS = 'auth/LOGIN_SUCCESS'
