export const LOGIN_SUBMIT = 'auth/LOGIN_SUBMIT'
export const LOGIN_LOADING = 'auth/LOGIN_LOADING'
export const LOGIN_SUBMIT_CANCEL = 'auth/LOGIN_SUBMIT_CANCEL'
export const LOGIN_ERROR = 'auth/LOGIN_ERROR'
export const LOGIN_SUCCESS = 'auth/LOGIN_SUCCESS'
