export const GET_USER_LISTS = 'userLists/GET_USER_LISTS'
export const CREATE_USER_LIST = 'userLists/CREATE_USER_LIST'
export const CREATE_USER_LIST_START = 'userLists/CREATE_USER_LIST_START'
export const CREATE_USER_LIST_SUCCESS = 'userLists/CREATE_USER_LIST_SUCCESS'
export const CREATE_USER_LIST_ERROR = 'userLists/CREATE_USER_LIST_ERROR'

export const REQUEST_USER_LISTS_START = 'userLists/REQUEST_USER_LISTS_START'
export const REQUEST_USER_LISTS_SUCCESS = 'userLists/REQUEST_USER_LISTS_SUCCESS'
export const REQUEST_USER_LISTS_ERROR = 'userLists/REQUEST_USER_LISTS_ERROR'

export const REMOVE_USER_LIST = 'userLists/REMOVE_USER_LIST'
