export const SET_MOVIE_ID = 'movie/SET_MOVIE_ID'

export const GET_MOVIE_INFO = 'movie/GET_MOVIE_INFO'
export const REQUEST_MOVIE_INFO_START = 'movie/REQUEST_MOVIE_INFO_START'
export const REQUEST_MOVIE_INFO_SUCCESS = 'movie/REQUEST_MOVIE_INFO_SUCCESS'
export const REQUEST_MOVIE_INFO_ERROR = 'movie/REQUEST_MOVIE_INFO_ERROR'

export const GET_MOVIE_IMAGES = 'movie/GET_MOVIE_IMAGES'
export const REQUEST_MOVIE_IMAGES_START = 'movie/REQUEST_MOVIE_IMAGES_START'
export const REQUEST_MOVIE_IMAGES_SUCCESS = 'movie/REQUEST_MOVIE_IMAGES_SUCCESS'
export const REQUEST_MOVIE_IMAGES_ERROR = 'movie/REQUEST_MOVIE_IMAGES_ERROR'

export const GET_MOVIE_CREDITS = 'movie/GET_MOVIE_CREDITS'
export const REQUEST_MOVIE_CREDITS_SUCCESS = 'movie/REQUEST_MOVIE_CREDITS_SUCCESS'
export const REQUEST_MOVIE_CREDITS_START = 'movie/REQUEST_MOVIE_CREDITS_START '
export const REQUEST_MOVIE_CREDITS_ERROR = 'movie/REQUEST_MOVIE_CREDITS_ERROR '

export const GET_MOVIE_ACCOUNT_STATES = 'movie/GET_MOVIE_ACCOUNT_STATES'
export const REQUEST_MOVIE_ACCOUNT_STATES_START = 'movie/REQUEST_MOVIE_ACCOUNT_STATES_START'
export const REQUEST_MOVIE_ACCOUNT_STATES_ERROR = 'movie/REQUEST_MOVIE_ACCOUNT_STATES_ERROR'
export const REQUEST_MOVIE_ACCOUNT_STATES_SUCCESS = 'movie/REQUEST_MOVIE_ACCOUNT_STATES_SUCCESS'

export const ADD_MOVIE_TO_WATCHLIST = 'movie/ADD_MOVIE_TO_WATCHLIST'
export const ADD_MOVIE_TO_FAVORITES = 'movie/ADD_MOVIE_TO_FAVORITES'

export const ADD_MOVIE_TO_EXISTING_LIST = 'movie/ADD_MOVIE_TO_EXISTING_LIST'

export const ADD_MOVIE_TO_NEW_LIST = 'movie/ADD_MOVIE_TO_NEW_LIST'
export const ADD_MOVIE_TO_NEW_LIST_START = 'movie/ADD_MOVIE_TO_NEW_LIST_START'
export const ADD_MOVIE_TO_NEW_LIST_SUCCESS = 'movie/ADD_MOVIE_TO_NEW_LIST_SUCCESS'
