export const GET_MOVIE_INFO = 'movie/GET_MOVIE_INFO'
export const REQUEST_MOVIE_INFO_START = 'movie/REQUEST_MOVIE_INFO_START'
export const REQUEST_MOVIE_INFO_SUCCESS = 'movie/REQUEST_MOVIE_INFO_SUCCESS'
export const REQUEST_MOVIE_INFO_ERROR = 'movie/REQUEST_MOVIE_INFO_ERROR'

export const GET_MOVIE_IMAGES = 'movie/GET_MOVIE_IMAGES'
export const REQUEST_MOVIE_IMAGES_START = 'movie/REQUEST_MOVIE_IMAGES_START'
export const REQUEST_MOVIE_IMAGES_SUCCESS = 'movie/REQUEST_MOVIE_IMAGES_SUCCESS'
export const REQUEST_MOVIE_IMAGES_ERROR = 'movie/REQUEST_MOVIE_IMAGES_ERROR'

export const GET_MOVIE_CREDITS = 'movie/GET_MOVIE_CREDITS'
export const REQUEST_MOVIE_CREDITS_SUCCESS = 'movie/REQUEST_MOVIE_CREDITS_SUCCESS'
export const REQUEST_MOVIE_CREDITS_START = 'movie/REQUEST_MOVIE_CREDITS_START '
export const REQUEST_MOVIE_CREDITS_ERROR = 'movie/REQUEST_MOVIE_CREDITS_ERROR '
